Repository boostcampwm-2024/web32-BooMap, pull requests merged in 2024-11, with the labels that each got.

#49 [feature-1-1] 헤더 컴포넌트 퍼블리싱
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.tsx
  client/src/assets/addElement.png
  client/src/assets/ai.png
  client/src/assets/dashboard.png
  client/src/assets/export.png
  client/src/assets/list.png
  client/src/assets/logo.png
  client/src/assets/minus.png
  client/src/assets/plus.png
  client/src/assets/profile.png
  client/src/assets/react.svg
  client/src/assets/share.png
  client/src/assets/textFile.png
  client/src/assets/trash.png
  client/src/assets/voiceFile.png
  client/src/components/Header/Header.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/Main/index.tsx
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: FE, pair

#51 [Feature-1-2] 사이드바 퍼블리싱
  client/src/components/Header/index.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/components/Sidebar/OverviewButton.tsx
  client/src/components/Sidebar/index.tsx
  client/src/index.css
  client/src/pages/Main/index.tsx
Labels: FE, pair

#55 [Feature-1-fix] 빌드 관련 오류 해결
  client/src/main.tsx
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/tsconfig.node.tsbuildinfo
  client/tsconfig.tsbuildinfo
  client/vite.config.ts
Labels: FE, fix

#54 [Feature-8-3] 클라우드 환경 설정
  .dockerignore
  Dockerfile.api-server
  Dockerfile.nginx
  docker-compose.yml
  nginx/default.conf
  server/.dockerignore
  server/package-lock.json
  server/package.json
  server/src/configs/typeorm.config.ts
  server/test/app.e2e-spec.ts
Labels: BE

#56 [Feature-8] 테스트 API 작성 및 클라우드 환경 설정
  .dockerignore
  Dockerfile.api-server
  Dockerfile.nginx
  docker-compose.yml
  nginx/default.conf
  server/package-lock.json
  server/package.json
  server/src/configs/typeorm.config.ts
  server/test/app.e2e-spec.ts
Labels: BE

#60 [Feature-8-5] CI/CD 설정 추가
  .github/workflows/be-ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/fe-ci.yaml
  docker-compose.yml
  server/src/configs/typeorm.config.ts
Labels: BE, FE

#61 [Feature-1-fix] - 스타일 충돌 및 오류 수정
  client/src/App.css
  client/src/components/MainSection/ControlSection/index.tsx
  client/src/components/MainSection/index.tsx
  client/src/components/MindMapView/index.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/components/Sidebar/index.tsx
  client/src/index.css
  client/src/pages/Main/index.tsx
Labels: FE, fix

#64 [Feature-3-9] 유저는 요소를 생성하면 해당 상위 분류와 선으로 이어져 있다.
  client/package.json
  client/src/components/MindMapView/index.tsx
  client/src/konva_mindmap/ConnectedLine.tsx
  client/src/konva_mindmap/node.tsx
  client/src/konva_mindmap/test/line.test.ts
  client/src/konva_mindmap/types/location.ts
  client/src/konva_mindmap/utils/points.ts
  client/src/store/NodeListProvider.tsx
  client/src/types/Node.ts
Labels: FE

#65 [Feature-3-4] 유저는 마인드맵에 있는 개별 요소를 클릭하고 아래 삭제 버튼을 통해 삭제할 수 있다.
  client/src/components/MindMapView/index.tsx
  client/src/hooks/useHistoryState.ts
  client/src/hooks/useWindowKeyEventListener.ts
  client/src/store/NodeListProvider.tsx
  client/src/types/Node.ts
Labels: FE

#66 [Feature-3-8-fe] 요소들은 충돌이 발생하면 서로 비껴나간다
  client/package-lock.json
  client/package.json
  client/src/components/MindMapView/index.tsx
  client/src/hooks/useHistoryState.ts
  client/src/konva_mindmap/hooks/useLayerEvent.ts
  client/src/konva_mindmap/node.tsx
  client/src/konva_mindmap/test/collision.test.tsx
  client/src/konva_mindmap/utils/collision.ts
  client/src/store/NodeListProvider.tsx
  client/vite.config.ts
Labels: FE

#70 [Feature-3-10-fe] 유저는 마인드맵을 확대, 축소 시키거나 드래그 앤 드랍으로 포커스를 바꿀 수 있다.
  client/src/components/MindMapView/index.tsx
  client/src/konva_mindmap/events/ratioSizing.ts
  client/src/konva_mindmap/node.tsx
Labels: FE

#71 [Feature-3-2-fe] Canvas Element는 각각의 요소가 겹치지 않게 캔버스 위에 그려진다.
  client/src/components/MindMapView/index.tsx
  client/src/konva_mindmap/hooks/useAdjustedStage.ts
  client/src/konva_mindmap/node.tsx
  client/src/konva_mindmap/utils/initializeNodePosition.ts
  client/src/store/NodeListProvider.tsx
Labels: FE

#75 [Feature-3-5-fe] 유저는 마인드맵에 있는 개별 요소를 더블클릭을 하면 수정할 수 있다.
  client/package-lock.json
  client/package.json
  client/src/konva_mindmap/EditableText.tsx
  client/src/konva_mindmap/EditableTextInput.tsx
  client/src/konva_mindmap/node.tsx
Labels: FE

#77 [Feature-4-1] 서버에서 JSON 데이터가 오면 클라이언트는 이를 파싱하여 List Element로 변환한다.
  client/src/components/MainSection/ControlSection/ListView/NodeList.tsx
  client/src/components/MainSection/ControlSection/ListView/index.tsx
Labels: FE

#78 [Feature-3-11-be] 소켓 통신 예외처리 로직 추가
  .github/workflows/fe-ci.yaml
  .gitignore
  Dockerfile.api-server
  api-server/.eslintrc.js
  api-server/.gitignore
  api-server/.prettierrc
  api-server/README.md
  api-server/nest-cli.json
  api-server/package-lock.json
  api-server/package.json
  api-server/src/app.module.ts
  api-server/src/configs/index.ts
  api-server/src/configs/logger.config.ts
  api-server/src/configs/redis.config.ts
  api-server/src/configs/typeorm.config.ts
  api-server/src/main.ts
  api-server/src/middlewares/logger.middleware.ts
  api-server/src/modules/connection/connection.controller.spec.ts
  api-server/src/modules/connection/connection.controller.ts
  api-server/src/modules/connection/connection.module.ts
  api-server/src/modules/connection/connection.service.spec.ts
  api-server/src/modules/connection/connection.service.ts
  api-server/src/modules/test/dto/test.dto.ts
  api-server/src/modules/test/entity/test.entity.ts
  api-server/src/modules/test/test.controller.spec.ts
  api-server/src/modules/test/test.controller.ts
  api-server/src/modules/test/test.module.ts
  api-server/src/modules/test/test.service.spec.ts
  api-server/src/modules/test/test.service.ts
  api-server/test/app.e2e-spec.ts
  api-server/test/jest-e2e.json
  api-server/tsconfig.build.json
  api-server/tsconfig.json
  socket-server/src/app.module.ts
  socket-server/src/configs/index.ts
  socket-server/src/configs/logger.config.ts
  socket-server/src/exceptionfilter/ws.exceptionFilter.ts
  socket-server/src/modules/map/exceptions/exception.ts
  socket-server/src/modules/map/exceptions/index.ts
  socket-server/src/modules/map/map.gateway.ts
  socket-server/src/modules/map/map.module.ts
  socket-server/src/modules/map/map.service.ts
Labels: BE

#76 [Feature-6-8-fe] 유저는 로그인 상태에 따라 회원/비회원 UI를 볼 수 있다.
  client/src/assets/dashbordIcon.png
  client/src/assets/search.png
  client/src/assets/whitePlus.png
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/Dashboard/index.tsx
  client/src/components/MainSection/ControlSection/index.tsx
  client/src/components/MainSection/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/hooks/useSection.ts
  client/src/index.css
  client/tailwind.config.js
Labels: FE

#80 [Feature-3-jjambbong]리팩토링 및 기능추가와 마인드맵 각 노드 기능 통합(짬뽕먹고싶네)
  client/index.html
  client/src/components/MindMapView/ToolMenu.tsx
  client/src/components/MindMapView/index.tsx
  client/src/hooks/useHistoryState.ts
  client/src/konva_mindmap/components/ConnectedLine.tsx
  client/src/konva_mindmap/components/DrawMindMap.tsx
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/EditableTextInput.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/konva_mindmap/hooks/useAdjustedStage.ts
  client/src/konva_mindmap/hooks/useDimension.ts
  client/src/konva_mindmap/node.tsx
  client/src/konva_mindmap/types/Node.ts
  client/src/konva_mindmap/types/dimension.ts
  client/src/konva_mindmap/utils/collision.ts
  client/src/konva_mindmap/utils/initializeNodePosition.ts
  client/src/konva_mindmap/utils/vector.ts
  client/src/store/NodeListProvider.tsx
Labels: FE

#84 [Feature-3-11-fix] 노드 추가, 삭제, 수정 로직 변경
  Dockerfile.nginx
  api-server/src/configs/typeorm.config.ts
  api-server/src/modules/connection/connection.controller.ts
  api-server/src/modules/connection/connection.service.ts
  socket-server/.prettierrc
  socket-server/src/app.module.ts
  socket-server/src/configs/typeorm.config.ts
  socket-server/src/exceptionfilter/ws.exceptionFilter.ts
  socket-server/src/main.ts
  socket-server/src/middlewares/logger.middleware.ts
  socket-server/src/modules/map/entity/mindmap.entity.ts
  socket-server/src/modules/map/entity/node.entity.ts
  socket-server/src/modules/map/entity/user.entity.ts
  socket-server/src/modules/map/exceptions/exception.ts
  socket-server/src/modules/map/map.gateway.ts
  socket-server/src/modules/map/map.service.ts
  socket-server/src/pipes/mindmap.validation.pipe.ts
  socket-server/src/pipes/ws.validation.pipe.ts
Labels: ⚡️ BE, 🛠️ fix

#85 [Feature-3-11-fix-be] 노드 생성, 삭제 로직 수정 && 소켓 연결시 현재 데이터 전송 추가
  .github/workflows/deploy.yaml
  socket-server/src/modules/map/dto/mindmap.update.dto.ts
  socket-server/src/modules/map/dto/node.delete.dto.ts
  socket-server/src/modules/map/exceptions/exception.ts
  socket-server/src/modules/map/map.gateway.ts
  socket-server/src/modules/map/map.service.ts
Labels: ⚡️ BE, 🛠️ fix

#87 [Feature-3-jjambbong2] 노드 조작 관련 기능 결합 및 신규 기능 추가
  client/src/components/Header/index.tsx
  client/src/components/MainSection/ControlSection/ListView/NodeItem.tsx
  client/src/components/MainSection/ControlSection/ListView/NodeList.tsx
  client/src/components/MainSection/ControlSection/ListView/index.tsx
  client/src/components/MindMapView/CanvasButtons.tsx
  client/src/components/MindMapView/DeleteConfirmModal.tsx
  client/src/components/MindMapView/NoNodeInform.tsx
  client/src/components/MindMapView/ToolMenu.tsx
  client/src/components/MindMapView/index.tsx
  client/src/constants/color.ts
  client/src/hooks/useHistoryState.ts
  client/src/hooks/useNodeActions.ts
  client/src/konva_mindmap/components/DrawMindMap.tsx
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/konva_mindmap/events/ratioSizing.ts
  client/src/konva_mindmap/hooks/useCollisionDetection.ts
  client/src/konva_mindmap/hooks/useDimension.ts
  client/src/konva_mindmap/utils/collision.ts
  client/src/konva_mindmap/utils/download.ts
  client/src/konva_mindmap/utils/following.ts
  client/src/store/NodeListProvider.tsx
  client/src/store/useStageStore.ts
  client/src/types/Node.ts
Labels: 🎨 FE, 🛠️ fix

#90 [Feature-7-1-be- fix] 모듈 임포트 수정 및 OAuth 받아오는 정보 추가
  api-server/package-lock.json
  api-server/package.json
  api-server/src/app.module.ts
  api-server/src/interface/authenticated.request.interface.ts
  api-server/src/interface/index.ts
  api-server/src/modules/auth/auth.controller.ts
  api-server/src/modules/auth/auth.module.ts
  api-server/src/modules/auth/strategies/github.strategy.ts
  api-server/src/modules/auth/strategies/kakao.strategy.ts
  api-server/src/modules/connection/connection.controller.ts
  api-server/src/modules/connection/connection.module.ts
  api-server/src/modules/connection/connection.service.ts
  api-server/src/modules/user/dto/index.ts
  api-server/src/modules/user/dto/user.create.dto.ts
  api-server/src/modules/user/dto/user.info.dto.ts
  api-server/src/modules/user/entities/user.entity.ts
  api-server/src/modules/user/user.controller.ts
  api-server/src/modules/user/user.module.ts
  api-server/src/modules/user/user.service.ts
  socket-server/package-lock.json
  socket-server/package.json
  socket-server/src/app.module.ts
  socket-server/src/modules/map/entity/user.entity.ts
Labels: ⚡️ BE, 🛠️ fix

#89 [Feature-1-2] 사이드바 퍼블리싱 추가 - 사이드바를 토글로 열고 닫을 수 있다.
  client/src/components/Sidebar/ToggleButton.tsx
  client/src/components/Sidebar/index.tsx
  client/src/pages/Main/index.tsx
Labels: 🎨 FE

#91 [Feature-8-1-fe] Story8 태스크들 & provider 위치 수정
  client/package-lock.json
  client/package.json
  client/src/components/MainSection/ControlSection/TextUpload.tsx
  client/src/components/MainSection/MindMapView.tsx
  client/src/components/MainSection/index.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/DeleteConfirmModal.tsx
  client/src/components/MindMapCanvas/NoNodeInform.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/Minutes/QuillEditor/index.tsx
  client/src/components/Minutes/QuillEditor/snow.css
  client/src/components/Minutes/index.tsx
  client/src/constants/textUploadLimit.ts
  client/src/hooks/useMinutes.ts
  client/src/pages/Main/index.tsx
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#92 [feature-0] 도커 개발환경 추가
  .gitignore
  Docker-compose.dev.yml
  Dockerfile.api-server.dev
  Dockerfile.fe.dev
  Dockerfile.nginx.dev
  Dockerfile.socket-server.dev
  client/vite.config.ts
  nginx/dev.conf
Labels: ⚡️ BE, 🎨 FE

#95 [Feature-6-5-fe] 대시보드 삭제 & 검색 기능 구현
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/utils/extractDate.ts
Labels: 🎨 FE

#100 [Feature-7-1-be-fix] 모듈 import 수정
  BE/apps/api-server/src/modules/auth/auth.module.ts
  BE/apps/api-server/src/modules/connection/connection.module.ts
  BE/apps/api-server/src/modules/user/user.module.ts
  BE/apps/api-server/src/strategies/github.strategy.ts
  BE/apps/api-server/src/strategies/index.ts
  BE/apps/api-server/src/strategies/jwt.strategy.ts
  BE/apps/api-server/src/strategies/kakao.strategy.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
Labels: ⚡️ BE, 🛠️ fix

#96 [Feature-3-7-fe] 유저의 액션(이동, 삭제, 추가, 수정)이 이루어지면 서버에 반영된다.
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/socket-server/src/pipes/ws.validation.pipe.ts
  client/package-lock.json
  client/package.json
  client/src/api/mindmap.api.ts
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/components/MindMapMainSection/MindMapView.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/hooks/useHistoryState.ts
  client/src/hooks/useWindowEventListener.ts
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/konva_mindmap/hooks/useAdjustedStage.ts
  client/src/konva_mindmap/utils/findRootNodeKey.ts
  client/src/konva_mindmap/utils/following.ts
  client/src/konva_mindmap/utils/initializeNodePosition.ts
  client/src/main.tsx
  client/src/store/NodeListProvider.tsx
  client/src/store/SocketSlice.ts
  client/src/types/NodePayload.ts
Labels: 🎨 FE

#102 [Feature-8-3-fix-fe] react-quill에서 tiptap으로 변경 & 단축키 미리보기 추가
  client/package-lock.json
  client/package.json
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/Minutes/QuillEditor/index.tsx
  client/src/components/Minutes/QuillEditor/snow.css
  client/src/components/Minutes/Tiptap/MenuBar.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/Minutes/Tiptap/styles.css
  client/src/components/Minutes/Tiptap/utils/codeBlockIndent.ts
  client/src/components/Minutes/Tiptap/utils/indent.ts
  client/src/components/Minutes/index.tsx
Labels: 🎨 FE

#104 [feature-3-7-fix-fe] 누락된 소켓 연결 시나리오 추가 및 이벤트 리스너 중복 부착으로 인한 history 문제 해결
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/hooks/useHistoryState.ts
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/store/NodeListProvider.tsx
  client/src/store/useSocketStore.ts
Labels: 🎨 FE

#109 [Feature-3-16-fe] 사용자는 각 단축키를 통해 캔버스의 마인드맵을 조작할 수 있다.
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/Minutes/index.tsx
  client/src/hooks/useNodeActions.ts
  client/src/hooks/useWindowKeyEventListener.ts
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#108 [feature-3-7-fix-fe] 소켓 disconnect시 상태 정리 및 enter시 updateNode 중복 호출 문제 해결
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#111 [Dev-fe-fix] dev 머지 후 충돌 & 에러들 수정
  client/package.json
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#113 [Feature-3-17-fe] 벡터 함수 수정 & 초기 비율 수정 & 노드 첫 생성 위치 수정
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/hooks/useAdjustedStage.ts
  client/src/konva_mindmap/utils/vector.ts
Labels: 🎨 FE

#114 [Feature-3-6-fix-fe] 노드 추가 Input창 포커싱 관련 문제
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/components/MindMapMainSection/ControlSection/index.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/EditableTextInput.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/store/NodeListProvider.tsx
  client/src/types/Node.ts
Labels: 🎨 FE, 🛠️ fix

#119 [feature-4-10-fe] 리스트에서 이루어지는 모든 조작은 소켓 통신을 통해 다른 이용자들에게 공유된다.
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/hooks/useNodeActions.ts
Labels: 🎨 FE

#120 [feature-3-7-fix-fe] 노드 수정시 원래 content와 동일할 경우 요청 전송 방지
  client/src/hooks/useNodeActions.ts
  client/src/konva_mindmap/components/EditableText.tsx
Labels: 🎨 FE

#121 [Feature-6-be] 대시보드 조회 기능 구현 및 이전 마인드맵 불러오기 기능 구현
  BE/.prettierrc
  BE/apps/api-server/package.json
  BE/apps/api-server/src/app.module.ts
  BE/apps/api-server/src/guards/optional.jwt.guard.spec.ts
  BE/apps/api-server/src/modules/auth/auth.controller.ts
  BE/apps/api-server/src/modules/auth/auth.module.ts
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/api-server/src/modules/connection/connection.module.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.controller.spec.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.controller.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.module.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.service.spec.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.service.ts
  BE/apps/api-server/src/modules/mindmap/dto/index.ts
  BE/apps/api-server/src/modules/mindmap/dto/update.mindmap.dto.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.controller.spec.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.controller.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.module.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/modules/node/dto/node.dto.ts
  BE/apps/api-server/src/modules/node/dto/update.node.dto.ts
  BE/apps/api-server/src/modules/node/node.module.ts
  BE/apps/api-server/src/modules/node/node.service.spec.ts
  BE/apps/api-server/src/modules/node/node.service.ts
  BE/apps/api-server/src/modules/user/user.controller.ts
  BE/apps/api-server/src/modules/user/user.module.ts
  BE/apps/api-server/src/modules/user/user.service.ts
  BE/apps/api-server/src/strategies/index.ts
  BE/apps/socket-server/package.json
  BE/apps/socket-server/src/app.module.ts
  BE/apps/socket-server/src/modules/auth/auth.module.ts
  BE/apps/socket-server/src/modules/map/exceptions/exception.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  BE/libs/entity/src/enum/role.enum.ts
  BE/libs/entity/src/index.ts
  BE/libs/entity/src/mindmap.entity.ts
  BE/libs/entity/src/user.entity.ts
  BE/libs/entity/src/user.mindmap.role.ts
  BE/libs/jwt/src/index.ts
  BE/libs/jwt/src/jwt.strategy.ts
  BE/libs/jwt/src/optional.jwt.guard.ts
  BE/libs/jwt/tsconfig.lib.json
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/tsconfig.json
  client/package-lock.json
Labels: ⚡️ BE

#122 [Feature-jjambbong3-fe] share 모달 추가 & 전체 모달들 통일 & 회의록 관련 에러 수정
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/index.tsx
  client/src/components/DeleteMindMapModal/index.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapHeader/MindMapHeaderButtons.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/Minutes/index.tsx
  client/src/components/ShareModal/index.tsx
  client/src/components/common/Modal.tsx
Labels: 🎨 FE, 🛠️ fix

#125 [Feature-3-7-fix-fe] 변경된 서버 로직과 프론트엔드 초기 데이터 불러오는 방식 동기화 / package-lock.json 복구
  client/package-lock.json
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#127 [Feature-0-5-fe] 비회원 유저는 새로운 마인드맵 누르기를 누르면 유저 권한의 마인드맵이 생성되고 회의록 권한은 해당 유저만 사용이 가능하다.
  client/src/api/index.ts
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/LoginModal/index.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/hooks/useAuth.ts
  client/src/store/NodeListProvider.tsx
  client/src/store/useAuthStore.ts
  client/src/store/useSocketStore.ts
  client/src/utils/localstorage.ts
  client/src/utils/token.ts
Labels: 🎨 FE

#129 [Feature-6-1,2-fe] 유저는 기존에 생성했던 마인드맵 히스토리를 눌러 해당 마인드맵 캔버스로 이동할 수 있다.
  client/src/api/dashboard.api.ts
  client/src/api/fetchHooks/useDashBoard.ts
  client/src/api/fetchHooks/useDeleteMindMap.ts
  client/src/api/mindmap.api.ts
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/NoMindMap.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/konva_mindmap/types/dashboard.ts
Labels: 🎨 FE

#131 [Feature-6-10-fe]대시보드에 있을 때, 기존 작업 내역이 있는 경우 사이드바의 다른 버튼들을 누르면 최근 방문했던 마인드맵으로 돌아가기와 새로운 마인드맵 누르기 버튼이 모달로 생기며 두 가지 선택지를 통해 마인드맵에 접근할 수 있다.
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Sidebar/LatestMindMapModal.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/store/NodeListProvider.tsx
  client/src/utils/localstorage.ts
Labels: 🎨 FE

#133 [Feature-3-19-fe] 소유자는 헤더의 마인드맵 제목이나 회의록의 내용을 변경할 수 있으며, 변경 내용은 broadcast되어 동시 편집중인 모든 사람들에게 보인다.
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/Minutes/index.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/components/Sidebar/OverviewButton.tsx
  client/src/hooks/useContent.ts
  client/src/hooks/useMindMapTitle.ts
  client/src/konva_mindmap/utils/throttle.ts
  client/src/store/NodeListProvider.tsx
  client/src/store/useSocketStore.ts
  client/src/types/NodePayload.ts
Labels: 🎨 FE

#134 [Feature-jjambbong-be] STORY-3, STORY-4, STORY-6 오류 수정 및 기능 구현
  BE/apps/api-server/src/app.module.ts
  BE/apps/api-server/src/modules/auth/auth.controller.ts
  BE/apps/api-server/src/modules/auth/auth.service.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.controller.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.service.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/modules/node/node.service.ts
  BE/apps/api-server/src/modules/pubsub/publisher.service.spec.ts
  BE/apps/api-server/src/modules/pubsub/publisher.service.ts
  BE/apps/api-server/src/modules/pubsub/pubsub.module.ts
  BE/apps/api-server/src/modules/pubsub/subscriber.service.spec.ts
  BE/apps/api-server/src/modules/pubsub/subscriber.service.ts
  BE/apps/socket-server/package.json
  BE/apps/socket-server/src/app.module.ts
  BE/apps/socket-server/src/exceptions/exception.ts
  BE/apps/socket-server/src/exceptions/index.ts
  BE/apps/socket-server/src/guard/ws.jwt.auth.guard.ts
  BE/apps/socket-server/src/main.ts
  BE/apps/socket-server/src/modules/auth/auth.module.ts
  BE/apps/socket-server/src/modules/map/dto/ai.request.dto.ts
  BE/apps/socket-server/src/modules/map/dto/index.ts
  BE/apps/socket-server/src/modules/map/dto/node/create.node.dto.ts
  BE/apps/socket-server/src/modules/map/dto/node/delete.node.dto.ts
  BE/apps/socket-server/src/modules/map/dto/node/location.dto.ts
  BE/apps/socket-server/src/modules/map/dto/node/update.mindmap.dto.ts
  BE/apps/socket-server/src/modules/map/dto/node/update.node.dto.ts
  BE/apps/socket-server/src/modules/map/dto/update.content.dto.ts
  BE/apps/socket-server/src/modules/map/dto/update.title.dto.ts
  BE/apps/socket-server/src/modules/map/exceptions/exception.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.module.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  BE/apps/socket-server/src/modules/pubsub/publisher.service.spec.ts
  BE/apps/socket-server/src/modules/pubsub/publisher.service.ts
  BE/apps/socket-server/src/modules/pubsub/pubsub.module.ts
  BE/apps/socket-server/src/modules/pubsub/subscriber.service.spec.ts
  BE/apps/socket-server/src/modules/pubsub/subscriber.service.ts
  BE/apps/socket-server/test/app.e2e-spec.ts
  BE/libs/config/src/redis.config.ts
  BE/libs/entity/src/node.entity.ts
  BE/libs/interface/src/authenticated.request.interface.ts
  BE/libs/interface/src/index.ts
  BE/libs/interface/tsconfig.lib.json
  BE/package-lock.json
Labels: ⚡️ BE, 🛠️ fix

#135 [Feature-3-2-fix-fe] 마인드맵 재정렬 로직 수정 & 모달 UI 통일 &
  client/src/components/DeleteMindMapModal/index.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/DeleteConfirmModal.tsx
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/ShareModal/index.tsx
  client/src/konva_mindmap/components/EditableTextInput.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/hooks/useAdjustedStage.ts
  client/src/konva_mindmap/hooks/useDimension.ts
  client/src/konva_mindmap/utils/initializeNodePosition.ts
  client/src/konva_mindmap/utils/nodeAttrs.ts
Labels: 🎨 FE

#136 HOTFIX : 그룹을 선택하고 다른 노드를 클릭했을 때 그룹 선택한 노드들이 딸려오는 에러 해결
  .gitignore
  client/src/components/MindMapHeader/Profile.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
Labels: 🎨 FE

#137 [feature-3-7-fix-fe] io 객체 생성 url 변경 / connection 상태에 따라 비정상적인 연결 해제시 에러 페이지 표시
  client/src/pages/layout/index.tsx
  client/src/store/useSocketStore.ts
Labels: 🎨 FE

#138 [Feature-0-fix] 배포 설정 변경
  .github/workflows/deploy.yaml
  BE/Dockerfile.api
  BE/Dockerfile.socket
  BE/apps/api-server/src/app.module.ts
  BE/apps/socket-server/src/app.module.ts
  docker-compose.yml
  nginx/default.conf
Labels: 🛠️ fix, ✨ deploy

#141 [Feature-0-3-fix-fe] 대시보드 UI 수정 & 로그인 모달 UI 수정
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/Dashboard/NoMindMap.tsx
  client/src/components/LoginModal/index.tsx
Labels: 🎨 FE

#142 5주차 배포2
  BE/Dockerfile.api
  BE/Dockerfile.socket
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/Dashboard/NoMindMap.tsx
  client/src/components/LoginModal/index.tsx
Labels: 🛠️ fix, ✨ deploy

#150 [deploy-be-fix] 소켓 jwt 가드 수정 및 user api 수정
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.service.ts
  BE/apps/api-server/src/modules/user/user.service.ts
  BE/apps/socket-server/src/guard/ws.jwt.auth.guard.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
Labels: 🛠️ fix, ✨ deploy

#149 [Feature-6-9-fe-fix] 대시보드에서 마인드맵 이동시 api 호출과 소켓 연결 후 이동 보완
  client/src/api/mindmap.api.ts
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/store/useAuthStore.ts
  client/src/store/useSocketStore.ts
Labels: 🎨 FE, 🛠️ fix

#151 5주차 배포 5
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/dashboard/dashboard.service.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/modules/user/user.service.ts
  BE/apps/socket-server/src/guard/ws.jwt.auth.guard.ts
  BE/apps/socket-server/src/main.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  client/src/api/mindmap.api.ts
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/store/NodeListProvider.tsx
  client/src/store/useAuthStore.ts
  client/src/store/useSocketStore.ts
  client/vite.config.ts
  docker-compose.yml
Labels: 🛠️ fix, ✨ deploy

#159 [Feature-3-7-fix-fe]
  client/src/components/MindMapMainSection/index.tsx
  client/src/hooks/useAuth.ts
  client/src/pages/layout/index.tsx
  client/src/store/useSocketStore.ts
Labels: 🎨 FE

#160 [Feature-modal-fe] 모달 hover 효과 통일 & png -> react-icons 변경
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/Dashboard/GuestNewMindMapModal.tsx
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/NoMindMap.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/DeleteMindMapModal/index.tsx
  client/src/components/LoginModal/index.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapCanvas/DeleteConfirmModal.tsx
  client/src/components/MindMapCanvas/NoNodeInform.tsx
  client/src/components/MindMapHeader/MindMapHeaderButtons.tsx
  client/src/components/MindMapHeader/ProfileModal.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/UploadBox.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
  client/src/components/common/NotFound.tsx
Labels: 🎨 FE

#163 [Feature-minutes-fix-fe] 회의록 z-index 수정
  client/src/components/Minutes/index.tsx
Labels: 🎨 FE, 🛠️ fix

#167 [Feature-socket-fix-fe] 회의록, 제목 관련 실시간 데이터 반영
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#170 [feature-socket-fix-fe] 루트 노드 삭제 방지
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/konva_mindmap/events/deleteNode.ts
Labels: 🎨 FE

#176 [feature-socket-fix-fe] 실수로 지운 로직 복구
  client/src/store/useSocketStore.ts
Labels: 🎨 FE

#179 [Feature-aitest-fe] aitest 페이지 & 단축키 창 토글 모드 추가
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/ShareModal/index.tsx
  client/src/main.tsx
  client/src/pages/TestPage.tsx
Labels: 🎨 FE, 🛠️ fix

#178 [Feature-3-fix-fe] 노드를 추가했을 때 input이 아닌 상태를 default로 설정 / 자동 select 조정 및 enter시 input 활성화 (마인드맵 영역)
  client/src/components/MindMapCanvas/NoNodeInform.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/hooks/useWindowKeyEventListener.ts
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/components/NewNode.tsx
  client/src/konva_mindmap/events/addNode.ts
Labels: 🎨 FE

#182 [Feature-minutes-fix2-fe] 회의록 들여쓰기 내어쓰기 안되던 오류 수정 & list도 들여쓰기 내어쓰기 되도록
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/Minutes/Tiptap/styles.css
  client/src/components/Minutes/Tiptap/utils/indent.ts
Labels: 🎨 FE, 🛠️ fix

#183 [Feature-3-fix-fe] 노드를 추가했을 때 input이 아닌 상태를 default로 설정 / 자동 select 조정 및 enter시 input 활성화 (리스트 영역)
  client/src/components/MindMapCanvas/NoNodeInform.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/hooks/useNodeActions.ts
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/store/NodeListProvider.tsx
  client/src/types/Node.ts
Labels: 🎨 FE

#184 [feature-0-fix-fe] 클로바X 기술지원 로고 추가
  client/src/assets/clovaX.png
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
Labels: 🎨 FE
