Repository boostcampwm-2024/web32-BooMap, pull requests merged in 2024-12, with the labels that each got.

#189 [feature-4-fix-fe] 리스트뷰에서 input이 비어있을 경우 원래 내용으로 돌아가지 않던 문제 해결
  client/src/hooks/useNodeActions.ts
Labels: 🎨 FE

#187 [feature-socket-fix-fe] 오프라인 상태일 때 모달 추가 / 토큰 받아오기 시점과 소켓 연결 시점 문제 해결
  client/src/assets/close.png
  client/src/components/LoginModal/index.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/components/OfflineModal/index.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/Toast/Toast.tsx
  client/src/pages/layout/index.tsx
  client/src/store/createSocketSlice.ts
Labels: 🎨 FE

#191 [Feature-tab-fe] tab, shift-tab시 요소들 이동 & 단축키 모달 창 위치 변경 및 애니메이션 추가
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/konva_mindmap/utils/findLastLeafNode.ts
  client/src/konva_mindmap/utils/findParentNodeKey.ts
  client/src/konva_mindmap/utils/moveToNode.ts
Labels: 🎨 FE, 🛠️ fix

#190 [Feature-2-fe] 변환용 텍스트파일 업로드 및 오류수정
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/common/ArrowBox.tsx
  client/src/constants/textUploadLimit.ts
  client/src/hooks/useUpload.ts
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/pages/Mindmap/index.tsx
  client/src/store/NodeListProvider.tsx
  client/src/store/createSocketSlice.ts
  client/src/types/NodePayload.ts
Labels: 🎨 FE

#192 [Feature-list-fix-fe] 리스트 아코디언 관련 함수 확장 & 타입 추가 & 수정
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/konva_mindmap/utils/findLastLeafNode.ts
  client/src/konva_mindmap/utils/findParentNodeKey.ts
  client/src/konva_mindmap/utils/moveToNode.ts
  client/src/konva_mindmap/utils/vector.ts
  client/src/types/Node.ts
Labels: 🎨 FE, 🛠️ fix

#193 [Feature-2-be] 텍스트 AI 기능 추가
  BE/apps/api-server/src/app.module.ts
  BE/apps/api-server/src/modules/ai/ai.module.ts
  BE/apps/api-server/src/modules/ai/ai.service.spec.ts
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/api-server/src/modules/node/node.service.ts
  BE/apps/api-server/src/modules/pubsub/publisher.service.ts
  BE/apps/api-server/src/modules/pubsub/pubsub.module.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.module.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.service.spec.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.service.ts
  BE/apps/socket-server/src/app.module.ts
  BE/apps/socket-server/src/exceptionfilter/ws.exceptionFilter.ts
  BE/apps/socket-server/src/guards/ws.jwt.auth.guard.ts
  BE/apps/socket-server/src/middlewares/logger.middleware.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.module.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  BE/apps/socket-server/src/modules/pubsub/pubsub.module.ts
  BE/apps/socket-server/src/modules/pubsub/subscriber.service.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.module.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.service.spec.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
  BE/libs/entity/src/node.entity.ts
  BE/libs/publisher/src/index.ts
  BE/libs/publisher/src/publisher.module.ts
  BE/libs/publisher/src/publisher.service.spec.ts
  BE/libs/publisher/src/publisher.service.ts
  BE/libs/publisher/tsconfig.lib.json
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/tsconfig.json
Labels: ⚡️ BE

#195 [Feature-0-fe-fix] 퍼블리싱 관련 오류 해결
  client/src/components/MindMapHeader/Profile.tsx
  client/src/components/MindMapHeader/ProfileModal.tsx
  client/src/constants/color.ts
  client/src/konva_mindmap/components/MindMapNode.tsx
Labels: 🎨 FE

#198 [Feature-2-be-fix] AI 요청 오류 수정
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/modules/node/node.service.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.service.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
Labels: ⚡️ BE, 🛠️ fix

#199 [feature-0-refactor] 서비스 로고 변경 / userSelect 제거
  README.md
  client/public/logo.png
  client/src/assets/error.ts
  client/src/assets/logo.png
  client/src/assets/notFound.webp
  client/src/components/Sidebar/index.tsx
  client/src/components/common/Error.tsx
  client/src/components/common/NotFound.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/auth/index.tsx
  client/src/pages/layout/index.tsx
Labels: 🎨 FE

#200 [feature-socket-fix] refactor : handleConnection 방식 변경 및 socketSlice 클린업 함수 추가
  client/src/store/NodeListProvider.tsx
  client/src/store/createSocketSlice.ts
Labels: 🎨 FE, 🛠️ fix

#203 [Feature-be-fix] typeORM cascade 옵션 수정
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/libs/entity/src/mindmap.entity.ts
  BE/libs/entity/src/node.entity.ts
  BE/libs/entity/src/user.entity.ts
  BE/libs/entity/src/user.mindmap.role.ts
Labels: ⚡️ BE, 🛠️ fix

#202 [Feature-1 fix-fe] 사이드바 토글 버튼 react icons로 변경
  client/src/assets/arrowDown.png
  client/src/components/Sidebar/ToggleButton.tsx
  client/src/main.tsx
  client/src/pages/TestPage.tsx
Labels: 🎨 FE

#205 [Deploy-week5-fix]
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/libs/entity/src/mindmap.entity.ts
  BE/libs/entity/src/node.entity.ts
  BE/libs/entity/src/user.entity.ts
  BE/libs/entity/src/user.mindmap.role.ts
  client/src/assets/arrowDown.png
  client/src/components/Sidebar/ToggleButton.tsx
  client/src/main.tsx
  client/src/pages/TestPage.tsx
Labels: 🛠️ fix, ✨ deploy

#209 [Feature-5-be] 텍스트 AI 요청 에러처리 추가 및 audio 파일 전송 api 추가
  BE/apps/api-server/common/constant.ts
  BE/apps/api-server/src/modules/ai/ai.controller.spec.ts
  BE/apps/api-server/src/modules/ai/ai.controller.ts
  BE/apps/api-server/src/modules/ai/ai.module.ts
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/api-server/src/modules/auth/auth.service.ts
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/pipes/file.validation.pipe.ts
  BE/apps/api-server/src/pipes/index.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
  BE/package-lock.json
  BE/package.json
  nginx/default.conf
  nginx/dev.conf
Labels: ⚡️ BE

#204 [Feature-2-2-fe] ai 업로드 로딩 모달 변경
  client/package-lock.json
  client/package.json
  client/src/assets/lottie/robot.json
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/common/aiSpinner.tsx
  client/src/hooks/useUpload.ts
  client/tsconfig.json
Labels: 🎨 FE

#212 [Feature-5-be-fix] file validation pipe 수정
  BE/apps/api-server/common/constant.ts
  BE/apps/api-server/src/middlewares/token.refresh.middleware.ts
  BE/apps/api-server/src/modules/ai/ai.module.ts
  BE/apps/api-server/src/modules/auth/auth.service.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
  BE/apps/api-server/src/pipes/audio.file.validation.pipe.ts
  BE/apps/api-server/src/pipes/index.ts
Labels: ⚡️ BE, 🛠️ fix

#210 [Feature-toast-fe] 노드 개수 15개, 전체 노드 개수 150개로 제한 & error들 toast로 보여주도록
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/ShowShortCut.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeList.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/components/common/Toast/Toast.tsx
  client/src/components/common/Toast/ToastContainer.tsx
  client/src/hooks/useToast.ts
  client/src/konva_mindmap/components/DrawMindMap.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/events/deleteNode.ts
  client/src/konva_mindmap/utils/checkNodeCount.ts
  client/src/konva_mindmap/utils/getNewNodePosition.ts
  client/src/konva_mindmap/utils/nodeAttrs.ts
  client/src/store/createSharedSlice.ts
  client/src/store/createSocketSlice.ts
Labels: 🎨 FE

#213 [Feature-scale-fe] scale에 따른 Text, input 창 크기 조정 & addNode 에러 수정
  client/src/components/MindMapCanvas/index.tsx
  client/src/konva_mindmap/components/DrawMindMap.tsx
  client/src/konva_mindmap/components/EditableText.tsx
  client/src/konva_mindmap/components/EditableTextInput.tsx
  client/src/konva_mindmap/components/MindMapNode.tsx
  client/src/konva_mindmap/events/addNode.ts
  client/src/types/Node.ts
Labels: 🎨 FE, 🛠️ fix

#215 [Feature-5-be] 음성 변환 AI 기능 구현
  BE/apps/api-server/common/constant.ts
  BE/apps/api-server/src/main.ts
  BE/apps/api-server/src/modules/ai/ai.controller.ts
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/api-server/src/modules/ai/dto/ai.dto.ts
  BE/apps/api-server/src/modules/ai/dto/audio.upload.dto.ts
  BE/apps/api-server/src/modules/ai/dto/clova.speech.request.dtd.ts
  BE/apps/api-server/src/modules/ai/dto/openai.request.dto.ts
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.service.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
  BE/libs/publisher/src/publisher.service.ts
  BE/package-lock.json
  BE/package.json
Labels: ⚡️ BE

#214 [Feature-5-5-fe] 음성 파일 업로드 api 변경에 따른 로직 수정 및 오류 수정
  client/src/api/ai.api.ts
  client/src/api/ai.ts
  client/src/api/auth.api.ts
  client/src/api/index.ts
  client/src/api/mindmap.api.ts
  client/src/api/test.ts
  client/src/assets/profile.png
  client/src/assets/search.png
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/MindMapHeader/MindMapHeaderButtons.tsx
  client/src/components/MindMapHeader/ProfileModal.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
  client/src/components/MindMapMainSection/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/constants/uploadLimit.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useTokenRefresh.ts
  client/src/hooks/useUpload.ts
  client/src/konva_mindmap/utils/nodeAttrs.ts
  client/src/main.tsx
  client/src/store/NodeListProvider.tsx
  client/src/store/useStageStore.ts
  client/src/utils/formData.ts
  client/tailwind.config.js
Labels: 🎨 FE

#219 [Feature-dev-hotfix] ai 요청 hotfix
  client/src/api/ai.api.ts
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
  client/src/constants/uploadLimit.ts
Labels: 🎨 FE

#220 [Feature-5-be] 오류수정
  BE/apps/api-server/src/common/constant.ts
  BE/apps/api-server/src/modules/ai/ai.controller.ts
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/pipes/audio.file.validation.pipe.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
Labels: ⚡️ BE, 🛠️ fix

#222 [Feature-modal-refactor-fe] AI text, voice 파일 업로드 시 모달 추가 & 모달 관련 파일들 리팩토링
  client/src/components/Dashboard/GuestDashBoard.tsx
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/MindMapCanvas/CanvasButtons.tsx
  client/src/components/MindMapHeader/MindMapHeaderButtons.tsx
  client/src/components/MindMapHeader/Profile.tsx
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
  client/src/components/Modal/ConfirmResetModal.tsx
  client/src/components/Modal/ConfirmUploadModal.tsx
  client/src/components/Modal/DeleteMindMapModal.tsx
  client/src/components/Modal/GuestNewMindMapModal.tsx
  client/src/components/Modal/LatestMindMapModal.tsx
  client/src/components/Modal/LoginModal.tsx
  client/src/components/Modal/OfflineModal.tsx
  client/src/components/Modal/ProfileModal.tsx
  client/src/components/Modal/ShareModal.tsx
  client/src/components/Sidebar/Overview.tsx
  client/src/pages/layout/index.tsx
Labels: 🎨 FE

#221 [Feature-dev-hotfix]음성파일 요청 관련 에러 처리
  client/src/api/ai.api.ts
  client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
  client/src/components/MindMapMainSection/ControlSection/UploadBox.tsx
  client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx
  client/src/store/NodeListProvider.tsx
Labels: 🎨 FE

#225 [Feature-5-be-fix]ai 요청 오류시 pending 상태 해제
  BE/apps/api-server/src/modules/ai/ai.controller.ts
  BE/apps/api-server/src/modules/subscriber/subscriber.service.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
Labels: ⚡️ BE, 🛠️ fix

#226 [Feature-5-be-fix] aiCount 검증 추가 및 감소 로직 response로 이동
  BE/apps/api-server/src/modules/ai/ai.service.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
Labels: ⚡️ BE, 🛠️ fix

#232 [feature-5-be-fix] dto 수정
  BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts
Labels: ⚡️ BE, 🛠️ fix

#237 [Feature-befix] user/info 요청 실패시 401 에러 반환
  BE/apps/api-server/src/modules/user/user.controller.ts
Labels: ⚡️ BE, 🛠️ fix

#238 [Feature-html-fe] html lang en -> ko & 노드 사이 선 위치 수정
  client/index.html
  client/src/konva_mindmap/utils/nodeAttrs.ts
Labels: 🎨 FE

#240 [Feature-be-fix] get Connection 403 에러 로그 추가, 게스트 마인드맵 생성 기본값 추가
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
Labels: ⚡️ BE, 🛠️ fix

#239 [Feature-dev-hotfix] 인코딩 문제 및 로그인 문제 해결
  client/src/api/index.ts
  client/src/store/createAuthSlice.ts
  client/src/store/createSharedSlice.ts
  client/src/store/createSocketSlice.ts
  client/src/utils/formData.ts
Labels: 🛠️ fix

#241 [6주차 배포-fix]
  BE/apps/api-server/src/modules/connection/connection.controller.ts
  BE/apps/api-server/src/modules/connection/connection.service.ts
  BE/apps/api-server/src/modules/user/user.controller.ts
  client/index.html
  client/src/api/index.ts
  client/src/konva_mindmap/utils/nodeAttrs.ts
  client/src/store/createAuthSlice.ts
  client/src/store/createSharedSlice.ts
  client/src/store/createSocketSlice.ts
  client/src/utils/formData.ts
Labels: 🛠️ fix, ✨ deploy

#243 [Feature-position-refactor-fe] 노드 재정렬 로직 수정 & 노드 생성 위치 로직 수정 & 노드 색상 변경
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/common/Toast/ToastContainer.tsx
  client/src/constants/color.ts
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/utils/getNewNodePosition.ts
  client/src/konva_mindmap/utils/initializeNodePosition.ts
Labels: 🎨 FE

#244 [feature-dev-hotfix] HOTFIX : 무한으로 refresh와 logout이 지속되던 문제 해결
  client/src/api/auth.api.ts
Labels: 🛠️ fix

#245 [Feature-be-fix] 6주차 배포 오류 수정
  BE/apps/api-server/src/modules/auth/auth.controller.ts
  BE/apps/api-server/src/modules/auth/auth.service.ts
  BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts
  BE/apps/api-server/src/strategies/kakao.strategy.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
Labels: ⚡️ BE, 🛠️ fix

#246 [6주차 배포-fix] 오류 수정
  BE/apps/api-server/src/modules/auth/auth.controller.ts
  BE/apps/api-server/src/modules/auth/auth.service.ts
  BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts
  BE/apps/api-server/src/strategies/kakao.strategy.ts
  BE/apps/socket-server/src/modules/map/map.gateway.ts
  BE/apps/socket-server/src/modules/map/map.service.ts
  client/src/api/auth.api.ts
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/ToolMenu.tsx
  client/src/components/MindMapHeader/index.tsx
  client/src/components/Minutes/Tiptap/index.tsx
  client/src/components/common/Toast/ToastContainer.tsx
  client/src/constants/color.ts
  client/src/konva_mindmap/events/addNode.ts
  client/src/konva_mindmap/utils/getNewNodePosition.ts
  client/src/konva_mindmap/utils/initializeNodePosition.ts
  client/src/store/NodeListProvider.tsx
  client/src/store/createSocketSlice.ts
Labels: 🛠️ fix, ✨ deploy

#248 [Feature-input-fe] input 활성화 시 요소 전체선택 ( 수정 바로 할 수 있도록 )
  client/src/components/MindMapHeader/index.tsx
  client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
  client/src/konva_mindmap/components/EditableTextInput.tsx
Labels: 🎨 FE

#252 [Feature-key-fix-fe]case문 안 break 추가
  client/src/components/MindMapCanvas/index.tsx
Labels: 🎨 FE, 🛠️ fix

#253 [feature-socket-fix] 사용자가 방에서 나갈 경우 nodeError가 비워지도록 설정
  client/src/store/createSocketSlice.ts
Labels: 🎨 FE

#255 [Feature-input-refactor-fe] 창 클릭시 복사 가능하도록 수정
  client/src/components/Modal/ShareModal.tsx
Labels: 🎨 FE

#257 6주차 최종 배포
  client/index.html
  client/public/thumbnail.png
  client/src/components/Dashboard/MindMapInfoItem.tsx
  client/src/components/Dashboard/UserDashBoard.tsx
  client/src/components/MindMapCanvas/index.tsx
  client/src/components/Modal/ShareModal.tsx
  client/src/store/createSocketSlice.ts
Labels: ✨ deploy

#260 [Feature-0-fix] CORS 설정 추가
  BE/apps/api-server/src/main.ts
  BE/apps/socket-server/src/main.ts
Labels: ⚡️ BE, 🛠️ fix

#261 최종 배포
  BE/apps/api-server/src/main.ts
  BE/apps/socket-server/src/main.ts
Labels: ✨ deploy

#262 [feature-dev-hotfix] logout 중복 호출 문제 해결
  client/src/api/auth.api.ts
  client/src/api/index.ts
Labels: 🎨 FE
